<?php
$holidays = [
    ['date' => '2026-01-01', 'name' => "New Year's Day", 'type' => 'regular', 'details' => 'Regular Holiday'],
    ['date' => '2026-01-16', 'name' => 'Lailatul Isra Wal Mi Raj', 'type' => 'special', 'details' => 'Muslim, Common Local Holiday'],
    ['date' => '2026-01-23', 'name' => 'First Philippine Republic Day', 'type' => 'special', 'details' => 'Special Working Day'],
    ['date' => '2026-02-17', 'name' => "Lunar New Year's Day", 'type' => 'special', 'details' => 'Special Non-working Holiday'],
    ['date' => '2026-02-19', 'name' => 'Ramadan Start', 'type' => 'special', 'details' => 'Observance, Muslim'],
    ['date' => '2026-02-25', 'name' => 'People Power Anniversary', 'type' => 'special', 'details' => 'Observance'],
    ['date' => '2026-03-20', 'name' => 'Eid al-Fitr (Tentative Date)', 'type' => 'regular', 'details' => 'Regular Holiday'],
    ['date' => '2026-03-20', 'name' => 'March Equinox', 'type' => 'special', 'details' => 'Season'],
    ['date' => '2026-04-02', 'name' => 'Maundy Thursday', 'type' => 'regular', 'details' => 'Regular Holiday'],
    ['date' => '2026-04-03', 'name' => 'Good Friday', 'type' => 'regular', 'details' => 'Regular Holiday'],
    ['date' => '2026-04-04', 'name' => 'Black Saturday', 'type' => 'special', 'details' => 'Special Non-working Holiday'],
    ['date' => '2026-04-04', 'name' => 'Black Saturday', 'type' => 'special', 'details' => 'Observance'],
    ['date' => '2026-04-05', 'name' => 'Easter Sunday', 'type' => 'special', 'details' => 'Observance'],
    ['date' => '2026-04-09', 'name' => 'The Day of Valor', 'type' => 'regular', 'details' => 'Regular Holiday'],
    ['date' => '2026-05-01', 'name' => 'Labor Day', 'type' => 'regular', 'details' => 'Regular Holiday'],
    ['date' => '2026-05-27', 'name' => 'Eid al-Adha (Tentative Date)', 'type' => 'regular', 'details' => 'Regular Holiday'],
    ['date' => '2026-05-28', 'name' => 'Eid al-Adha Day 2 (Tentative Date)', 'type' => 'special', 'details' => 'Muslim, Common Local Holiday'],
    ['date' => '2026-06-12', 'name' => 'Independence Day', 'type' => 'regular', 'details' => 'Regular Holiday'],
    ['date' => '2026-06-17', 'name' => 'Amun Jadid (Tentative Date)', 'type' => 'special', 'details' => 'Muslim, Common Local Holiday'],
    ['date' => '2026-06-21', 'name' => 'June Solstice', 'type' => 'special', 'details' => 'Season'],
    ['date' => '2026-07-27', 'name' => 'Founding Anniversary of Iglesia ni Cristo', 'type' => 'special', 'details' => 'Special Working Day'],
    ['date' => '2026-08-21', 'name' => 'Ninoy Aquino Day', 'type' => 'special', 'details' => 'Special Non-working Holiday'],
    ['date' => '2026-08-26', 'name' => 'Maulid un-Nabi (Tentative Date)', 'type' => 'special', 'details' => 'Muslim, Common Local Holiday'],
    ['date' => '2026-08-31', 'name' => 'National Heroes Day', 'type' => 'regular', 'details' => 'Regular Holiday'],
    ['date' => '2026-09-03', 'name' => 'Yamashita Surrender Day', 'type' => 'special', 'details' => 'Special Working Day'],
    ['date' => '2026-09-08', 'name' => 'Feast of the Nativity of Mary', 'type' => 'special', 'details' => 'Special Working Day'],
    ['date' => '2026-09-23', 'name' => 'September Equinox', 'type' => 'special', 'details' => 'Season'],
    ['date' => '2026-11-01', 'name' => "All Saints' Day", 'type' => 'special', 'details' => 'Special Non-working Holiday'],
    ['date' => '2026-11-02', 'name' => "All Souls' Day", 'type' => 'special', 'details' => 'Special Non-working Holiday'],
    ['date' => '2026-11-07', 'name' => "Sheikh Karim'ul Makhdum Day", 'type' => 'special', 'details' => 'Special Working Day'],
    ['date' => '2026-11-30', 'name' => 'Bonifacio Day', 'type' => 'regular', 'details' => 'Regular Holiday'],
    ['date' => '2026-12-08', 'name' => 'Feast of the Immaculate Conception', 'type' => 'special', 'details' => 'Special Non-working Holiday'],
    ['date' => '2026-12-22', 'name' => 'December Solstice', 'type' => 'special', 'details' => 'Season'],
    ['date' => '2026-12-24', 'name' => 'Christmas Eve', 'type' => 'special', 'details' => 'Special Non-working Holiday'],
    ['date' => '2026-12-25', 'name' => 'Christmas Day', 'type' => 'regular', 'details' => 'Regular Holiday'],
    ['date' => '2026-12-30', 'name' => 'Rizal Day', 'type' => 'regular', 'details' => 'Regular Holiday'],
    ['date' => '2026-12-31', 'name' => "New Year's Eve", 'type' => 'special', 'details' => 'Special Non-working Holiday'],
];
